- url: https://aboutdfir.com/feed
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-16T07:56:06.112492Z'
    score: 33
    matched_keywords:
    - apt
    - botnet
    - breach
    - campaign
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - malware
    - patch
    - payload
    - ransomware
    - vuln
    - zero-day
    discovered_via: common_path
    url_hash: 23c86d62d8de225e0fc137ecc1787fee61739781
- url: https://aboutdfir.com/feed/
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-16T07:56:08.765141Z'
    score: 33
    matched_keywords:
    - apt
    - botnet
    - breach
    - campaign
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - malware
    - patch
    - payload
    - ransomware
    - vuln
    - zero-day
    discovered_via: rel=alternate
    url_hash: cd09274df904f1b693916c560c6aac746ed4c1e4
- url: https://aboutdfir.com/rss
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-16T07:56:21.470249Z'
    score: 33
    matched_keywords:
    - apt
    - botnet
    - breach
    - campaign
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - malware
    - patch
    - payload
    - ransomware
    - vuln
    - zero-day
    discovered_via: common_path
    url_hash: b1899b2210f39da95cbe76df729687abce380ac2
- url: https://aboutdfir.com/rss/
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-16T07:56:18.914418Z'
    score: 33
    matched_keywords:
    - apt
    - botnet
    - breach
    - campaign
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - malware
    - patch
    - payload
    - ransomware
    - vuln
    - zero-day
    discovered_via: common_path
    url_hash: 714112b4ad6fe8f3c16147f089119749a1063796
