- url: https://blog.cryptographyengineering.com/feed
  title: A Few Thoughts on Cryptographic Engineering
  description: Some random thoughts about crypto. Notes from a course I teach. Pictures of my dachshunds.
  category: Crypto & Blockchain Security
- url: https://blog.chainalysis.com/feed/
  title: Chainalysis
  description: A timeout occurred Error code 524 Visit cloudflare.com for more information. 2024-01-08 21:23:13 UTC You Browser
    Working Frankfurt Cloudflare Working …
  category: Crypto & Blockchain Security
- url: https://cloudsecurityalliance.org/blog/feed/
  title: Cloud Security Alliance
  description: The Cloud Security Alliance (CSA) is the world’s leading organization dedicated to defining and raising awareness
    of best practices to …
  category: Crypto & Blockchain Security
- url: https://export.arxiv.org/rss/cs.CR/
  title: cs.CR updates on arXiv.org
  description: Computer Science -- Cryptography and Security (cs.CR) updates on the arXiv.org e-print archive
  category: Crypto & Blockchain Security
- url: https://www.sciencedaily.com/rss/computers_math/encryption.xml
  title: Encryption News -- ScienceDaily
  description: Encryption. Read the latest research on computer security and encryption methods here. Evaluate new methods
    for protecting sensitive data.
  category: Crypto & Blockchain Security
- url: https://www.globalencryption.org/feed/
  title: Global Encryption Coalition
  category: Crypto & Blockchain Security
- url: https://protos.com/feed
  title: Protos
  description: Informed crypto news
  category: Crypto & Blockchain Security
- url: https://rekt.news/rss/feed.xml
  title: Rekt
  description: Investigative journalism &amp; creative commentary
  category: Crypto & Blockchain Security
