- url: https://aboutdfir.com/feed
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-09T08:12:23.002610Z'
    score: 38
    matched_keywords:
    - apt
    - authentication
    - breach
    - bypass
    - campaign
    - cloud
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - patch
    - payload
    - ransomware
    - remote code execution
    - vuln
    - vulnerability
    - zero-day
    discovered_via: common_path
    url_hash: 23c86d62d8de225e0fc137ecc1787fee61739781
- url: https://aboutdfir.com/feed/
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-09T08:12:28.215395Z'
    score: 38
    matched_keywords:
    - apt
    - authentication
    - breach
    - bypass
    - campaign
    - cloud
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - patch
    - payload
    - ransomware
    - remote code execution
    - vuln
    - vulnerability
    - zero-day
    discovered_via: rel=alternate
    url_hash: cd09274df904f1b693916c560c6aac746ed4c1e4
- url: https://aboutdfir.com/rss
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-09T08:12:21.389236Z'
    score: 38
    matched_keywords:
    - apt
    - authentication
    - breach
    - bypass
    - campaign
    - cloud
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - patch
    - payload
    - ransomware
    - remote code execution
    - vuln
    - vulnerability
    - zero-day
    discovered_via: common_path
    url_hash: b1899b2210f39da95cbe76df729687abce380ac2
- url: https://aboutdfir.com/rss/
  category: Crypto & Blockchain Security
  title: AboutDFIR – The Definitive Compendium Project
  type: rss
  description: Digital Forensics / Incident Response
  discovery:
    discovered_at: '2026-02-09T08:12:32.095592Z'
    score: 38
    matched_keywords:
    - apt
    - authentication
    - breach
    - bypass
    - campaign
    - cloud
    - cve
    - dfir
    - exploit
    - incident
    - ioc
    - patch
    - payload
    - ransomware
    - remote code execution
    - vuln
    - vulnerability
    - zero-day
    discovered_via: common_path
    url_hash: 714112b4ad6fe8f3c16147f089119749a1063796
